version: '3'
services:
  screenshots:
    build:
      context: .
    volumes:
      - "./screenshots/__tests__/__image_snapshots__/:/app/screenshots/__tests__/__image_snapshots__"

  screenshots-update:
    build:
      context: .
    volumes:
      - "./screenshots/__tests__/__image_snapshots__/:/app/screenshots/__tests__/__image_snapshots__"
    command: npm run test:screenshots-update