name: "Examples: Quick Start"

on:
  push:
    branches:
      - 'master'
    paths:
      - 'examples/quick-start/**'
      - '.github/workflows/examples-quick-start.yml'
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: ./examples/quick-start
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: |
          npm ci
      - name: Build
        shell: bash
        run: |
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/quick-start
          destination_dir: examples/quick-start/dist
