name: Build and Publish @kaspersky/components storybook to GitHub Pages

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        name: Deploy to GitHub Pages
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: dist/storybook
          build_command: npm run build-storybook
