name: "@kaspersky/icons Storybook"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: ./packages/kaspersky-icons
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: |
          npm ci
      - name: Build Storybook
        shell: bash
        run: |
          npm run build-storybook
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/kaspersky-icons/storybook/icons
          destination_dir: icons
      # - name: Upload
      #   uses: actions/upload-pages-artifact@v2.0.0
      #   with: 
      #     path: packages/kaspersky-icons/storybook
      # - id: Deploy
      #   name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v2.0.3
