name: "@kaspersky/components Storybook"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: ./packages/kaspersky-components
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: |
          npm ci
      - name: Build Storybook
        shell: bash
        run: |
          npm run build-storybook
      - name: Upload
        uses: actions/upload-pages-artifact@v2.0.0
        with: 
          path: packages/kaspersky-components/storybook
      - id: Deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2.0.3
